version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws-backend-dev
          create-repo: true
          path: .
          repo: circleci-ecr-app-demo
          tag: "$AWS_REGION"
